### ISSUE TITLE
ESEF: calculations 1.1 new summation-item arcrole

### ISSUE THREAD

**Issue by TomaszBukowski123** [Arelle/Arelle#1445]
### What happened?

Hi again,

this time I tried to test Arelle against the new guidelines for Calculation 1.1 from the ESEF Reporting Manual and specifically about using the new summation-item link (Guidance 3.4.1). Here I actually see a slight variance in the links because in the Calculation 1.1 specification we clearly have https://xbrl.org/2023/arcrole/summation-item while the Manual uses https://www.xbrl.org/2023/arcrole/summation-item (it's about **www**). Regardless, when I swapped in the statement from old Conformance Suite from 2023 arcrole from old to to the new, Arelle produces a lot of, what seems to me, false positive validation errors:
![image](https://github.com/user-attachments/assets/fd2d912c-a897-4d4d-bffa-f9d163584274)
These entries are produced regardles if I select to check Calculations 1.1 or none at all.
Taking a quick peek into the code it appears to me that the problem lies specifically here:
![image](https://github.com/user-attachments/assets/3b86d7c7-3db4-499b-b887-591604a0c8f0)
I'm not sure that's the only place but i guess that's good start to look into it :)

### Documents

[TC1_valid.zip](https://github.com/user-attachments/files/18124889/TC1_valid.zip)

### Interface

GUI (arelleGUI)

### Version

2.35.17

### Download

GitHub release (bundled Python)

### Operating System

Windows

**Comment by austinmatherne-wk** [comment]
Hi @TomaszBukowski123 

Thank you for bringing up the inconsistency in the new ESEF reporting manual.

From the reporting manual:
> Arithmetical relationships defined in the calculation linkbase of an issuer’s taxonomy
MUST use the `https://www.xbrl.org/2023/arcrole/summation-item` arcrole as defined in
Calculation 1.1 specification.
In case of violation, the following message is recommended to be used:
Violation: “IncorrectSummationItemArcroleUsed”

The issue stems from the Calculation 1.1 specification not defining the arcrole with the www subdomain. You can review the [Calculation 1.1 schema here](https://www.xbrl.org/2023/calculation-1.1.xsd). The standard roles you've referenced are defined in the base 2.1 spec. Using a "custom arcrole" (any not defined in the 2.1 spec) without a valid roleRef defining it [requires us to raise base specification errors](https://www.xbrl.org/Specification/XBRL-2.1/REC-2003-12-31/XBRL-2.1-REC-2003-12-31+corrected-errata-2013-02-20.html#_3.5.2.5), which is why Arelle flags the www subdomain.

If interpreted strictly, the new reporting manual would effectively prevent any calculations from being defined. We expect that the ESEF conformance suite will address this discrepancy once it’s released. In the meantime, the beta version of the ESEF 2024 support in Arelle is recognizing this as an oversight and will accept the Calculation 1.1 arcrole without the www subdomain.

Best,
Austin

**Comment by TomaszBukowski123** [comment]
Hi @austinmatherne-wk 

Thanks for explaining this discrepancy and how it will be addressed in the future.

However, the problem with the discrepancy in the manual and the specification was found when finding the main problem, that is, that Arelle does not recognize any of the new roleRefs neither (the one with www nor the one without). Here is the validation result for the substituted link to the one with www and the file:
![image](https://github.com/user-attachments/assets/48cf1f1e-2ee5-4f17-a5be-bb76fdc21b7f)
[TC1_valid.zip](https://github.com/user-attachments/files/18162676/TC1_valid.zip)

in the first message I showed a screen shot of a place in the code:
https://github.com/Arelle/Arelle/blob/7e921bef62af1eeaf3d779255de685e41177b103/arelle/XbrlConst.py#L828-L841
 that seems to me at least one of the places that can generate the problem because `isStandardArcrole(role: str)` regardless of whether it gets https://xbrl.org/2023/arcrole/summation-item or https://www.xbrl.org/2023/arcrole/summation-item as a parameter returns `false`

Best regards,
Tomasz

**Comment by austinmatherne-wk** [comment]
The calc 1.1 arcrole is a "custom arcrole" (not defined in the base 2.1 spec) so a arcroleRef has to be present in the filing in order to use it:
```xml
<link:arcroleRef arcroleURI="https://xbrl.org/2023/arcrole/summation-item" xlink:type="simple" xlink:href="https://www.xbrl.org/2023/calculation-1.1.xsd#summation-item" />
```

Here's a modified version of the provided filing altered to correctly use the calc 1.1 summation roles:
[TC1_valid.zip](https://github.com/user-attachments/files/18169582/TC1_valid.zip)

**Comment by TomaszBukowski123** [comment]
Ah, now I understand where these validation results came from. Thank you very much for taking the time to explain this to me. and providing working test case.

Therefore, I close the issue.

Best regards,
Tomasz
