### ISSUE TITLE
CI mac distribution "is damaged"

### ISSUE THREAD

**Issue by austinmatherne-wk** [Arelle/Arelle#271]
The `Arelle.app` produced from the CI workflow can't be run without first removing extended attributes.

`xattr -dr com.apple.quarantine /Applications/Arelle.app`

<img width="372" alt="Screen Shot 2022-08-08 at 9 56 31 AM" src="https://user-images.githubusercontent.com/46454775/183464263-2166c7ad-867e-4fbb-aa7e-5ce59e52a44b.png">

**Comment by sagesmith-wf** [comment]
To add some context, the code sign wasn't ported to github actions since it is unclear if we want to continue signing as `Mark V` (I think it is also an unrecognized developer but I don't remember for sure). We will likely need to get an arelle developer id (I think we could continue using an arbitrary id such as `Mark V` to avoid the `xattr` command but then we would get an "unrecognized developer" dialog and have to `CMD + click open`). The original script has some code for signing, here is a permalink incase it is removed:

[Outdated Codesign Id](https://github.com/Arelle/Arelle/blob/a239d803ef1e88b377149905227762c16d1f90de/buildMacDist39.sh#L5-L9)
[Codesign logic](https://github.com/Arelle/Arelle/blob/a239d803ef1e88b377149905227762c16d1f90de/buildMacDist39.sh#L36-L79)
