### ISSUE TITLE
Run conformance suite after successful Tox run

### ISSUE THREAD

**Issue by ggravlingen** [Arelle/Arelle#394]
### What should we change and why?

Currently, it seems the conformance suite has to be manually triggered by a member in the Workiva team. It would improve the developer experience (and probably life for the Workiva team as well?) if those runs were triggered automatically instead. To reduce runner load, this could be done if the Tox test runs have been successfully completed.

It would also be kind of nice to not use the deploy feature to avoid spamming PR's with items as this makes it slightly more difficult to find review comments:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/21142447/193912838-7d1eec33-ad13-4bb7-8e86-5d38a6a5e461.png">

**Comment by sagesmith-wf** [comment]
FYI if you use ublock origin @stevenbronson-wk wrote a rule that can remove those `github.com##[data-url^="/Arelle/Arelle/pull/"][data-url*="/partials/deployed_event"]`. I believe they have to be manually triggered because they are not publicly available

**Comment by austinmatherne-wk** [comment]
We'd love to automatically run the conformance suites on PRs without approval. Unfortunately many of the suites are not public. The folks who created them charge membership fees for access and automatically downloading and running them without an approval step could get us in trouble if a PR was opened to exploit the workflow and redistribute the private conformance suites.

There are a couple of things we can do:
1. Document where to download or request the conformance suites from so that it's easier to run them locally.
2. Split the public and private conformance suites into separate workflows so that at least the public ones can run without an approval step.

**Comment by ggravlingen** [comment]
I understand the considerations here. (2) would be kind of neat and let's say this was in part a script that pulled down the public suites. That would in itself constitute documentation for others on how to pull down and run the tests locally.

I have such a script for the ESEF suite that I'm happy to submit as a PR just to get started.

**Comment by ggravlingen** [comment]
> FYI if you use ublock origin @stevenbronson-wk wrote a rule that can remove those `github.com##[data-url^="/Arelle/Arelle/pull/"][data-url*="/partials/deployed_event"]`. I believe they have to be manually triggered because they are not publicly available

I'm not familiar with that. Is that some sort of tool?

**Comment by austinmatherne-wk** [comment]
> (2) would be kind of neat and let's say this was in part a script that pulled down the public suites. That would in itself constitute documentation for others on how to pull down and run the tests locally.

The CI downloads conformance suites from our own AWS S3 bucket. We'd want any local script to download from the various publisher websites, but keep CI using S3 for reliability purposes (we don't want CI tests to fail because one of those websites is momentarily down).

> I have such a script for the ESEF suite that I'm happy to submit as a PR just to get started.

That would be great. I created #395 if you want to share what you have. We can expand on that to include the rest of the other public suites.

> I'm not familiar with that. Is that some sort of tool?

[ublock origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) is a browser extension and ad blocker which can be customized to block arbitrary webpage elements.

**Comment by ggravlingen** [comment]
Expanding on this and previous discussions on not supporting IDE specific config. Would you be open to opening the wiki? I could share my VS code config and link it to the script. If not, I could just share it in an issue. Maybe it will help someone get up and running.

**Comment by sagesmith-wf** [comment]
> Expanding on this and previous discussions on not supporting IDE specific config. Would you be open to opening the wiki? I could share my VS code config and link it to the script. If not, I could just share it in an issue. Maybe it will help someone get up and running.

That seems like a great idea to me

**Comment by austinmatherne-wk** [comment]
Agreed. I want to overhaul [arelle.readthedocs.io](https://arelle.readthedocs.io/) at some point, so we may end up transferring the wiki over there, but I'm not sure when I'll actually get to that.

I'll submit a ticket to have one of the sysadmins enable the wiki and update here once that's done.

**Comment by austinmatherne-wk** [comment]
@ggravlingen [the Arelle wiki](https://github.com/Arelle/Arelle/wiki) has been enabled. I don't think you'll have edit access, but I'll make sure your suggestions are added if you post them here, open a new issue, or clone the wiki and make changes on a branch.

**Comment by ggravlingen** [comment]
Closing this issue as there is now a wiki sharing details on how to setup a local test suite. This wiki page could possibly be expanded by the Workiva team with their knowledge when there is time for that.
