### ISSUE TITLE
ESEF.2.5.1.imageFormatNotSupported issue for SVG format with Base-64

### ISSUE THREAD

**Issue by lamechjil** [Arelle/Arelle#740]
### What happened?

In the latest Arelle version released, we are getting a strange validation error with regards to the Images and fonts rendered as Base-64 in the iXBRL XHTML.

[ESEF.2.5.1.incorrectMIMETypeSpecified] Header type jpg has wrong image type: /jpg - 549300WSX3VBUFFJOO66-2022-12-31-T01.html 111

[ESEF.2.5.1.imageFormatNotSupported] Images included in the XHTML document MUST be saved in PNG, GIF, SVG or JPG/JPEG formats: data:image/jpg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fEx. - 549300WSX3VBUFFJOO66-2022-12-31-T01.html 112

When we investigated further, we noted that the issues are occurring only for the pages with images where the size of the Base-64 code is quite large in the XHTML. This looks to us like this rule is newly added to Arelle, as we are not getting this validation errors in the older version of Arelle. 

We convert the images into SVG (svg+xml) based Base-64 which I believe an acceptable format as per ESEF.

### Documents

You can download the sample from here
https://filings.xbrl.org/filing/549300KGI78MKHO38N42-2022-12-31-ESEF-SI-3
[549300KGI78MKHO38N42-2022-12-31-en.zip](https://github.com/Arelle/Arelle/files/11800960/549300KGI78MKHO38N42-2022-12-31-en.zip)

### Interface

GUI (arelleGUI)

### Version

2.10.8

### Download

arelle.org (bundled Python)

### Operating System

Windows 10, Windows 11

**Comment by austinmatherne-wk** [comment]
Hello,

I investigated one of the SVGs in the document that was causing the error and it appears that the error is indeed appropriate. Using SVGs, even large ones, is perfectly valid, but the content within the SVG must also be valid.

The problem here is that the SVG is encapsulating a JPEG with an incorrect mime type.

For instance, on line 12131 of `549300KGI78MKHO38N42-2022-12-31-en.xhtml`, there is a base 64 encoded SVG:

```xml
<img id="pdf1" style="width:1286px; height:909px;" alt="" src="
	data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4w
```

Decoding the SVG reveals an image with a base 64 encoded JPEG:
```svg
<image clip-path="url(#c0_1)" preserveAspectRatio="none" x="-1" y="-1" width="1289" height="910" xlink:href="data:image/jpg;base64,/9j/4AAQSk...
```

This base 64 encoded JPEG is declared with the MIME type `image/jpg`. While `image/jpg` is recognized by some applications, it is not an official MIME type. The correct MIME type is `image/jpeg`. If you update the MIME types within your SVGs I expect all of those errors to go away.

I hope that help.
